<h3><?php echo $this->__('Shop by Brand'); ?></h3>

<?php $brandCollection = $this->getBrandCollection(); ?>
<?php if ($brandCollection->count() > 0): ?>

    <ul >
        <?php foreach ($brandCollection as $_brand): ?>
            <li style="width: 100%; float: left; margin: 5px; display: table">
                <div style="width: 80px; float: left">
                    <a href="<?php echo $this->helper('bluecom_brandexample/brand')->getBrandUrl($_brand); ?>" title="<?php echo $this->escapeHtml($_brand->getName()); ?>">
                        <img src="<?php echo Mage::getBaseUrl('media').'brand/'.$_brand->getImage()?>" style="width: 60px; height: 60px"/>
                    </a>
                </div>
                <div style="width: 120px; float: left; margin-top: 20px">
                    <a href="<?php echo $this->helper('bluecom_brandexample/brand')->getBrandUrl($_brand); ?>" title="<?php echo $this->escapeHtml($_brand->getName()); ?>">
                       <?php echo $_brand->getName()?>
                    </a>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

<?php else: ?>

    <?php echo $this->__('There are no brands to display at this time.'); ?>

<?php endif; ?>