<h1><?php echo $this->__('All Brand'); ?></h1>

<?php $brandCollection = $this->getBrandCollection(); ?>
<?php if ($brandCollection->count() > 0): ?>
    
    <ul>
        <?php foreach ($brandCollection as $_brand): ?>    
            <li style="width: 150px; float: left; margin: 10px; text-align: center">
                <a href="<?php echo $this->helper('bluecom_brandexample/brand')->getBrandUrl($_brand); ?>" title="<?php echo $this->escapeHtml($_brand->getName()); ?>">
                    <img src="<?php echo Mage::getBaseUrl('media').'brand/'.$_brand->getImage()?>" style="width: 148px; height: 148px"/>
                    <b><?php echo $_brand->getName()?></b>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    
<?php else: ?>
    
    <?php echo $this->__('There are no brands to display at this time.'); ?>
    
<?php endif; ?>